# Generated by Django 3.2.13 on 2022-06-25 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='toggle',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='toggle', to=settings.AUTH_USER_MODEL),
        ),
    ]
