# Generated by Django 3.2.13 on 2022-06-26 12:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_toggle_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='time',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='time',
            name='interval',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='time',
            name='toggle_status',
            field=models.BooleanField(),
        ),
    ]
