# Generated by Django 3.2.13 on 2022-07-01 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_follow_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
