# Generated by Django 3.2.13 on 2022-07-01 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_follow_created_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
    ]
